Visca\Bundle\LicomBundle\Entity\BettingOfferProviderGraphLabel:
  type: entity
  table: BettingOfferProvider_graphLabel
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 45
      nullable: false
