Visca\Bundle\LicomBundle\Entity\ChangeLog:
  type: entity
  table: changelog
  id:
    changeNumber:
      type: bigint
      length: 20
      column: change_number
    deltaSet:
      type: string
      length: 10
      column: delta_set
  fields:
    startDate:
      type: DateTimeUTCType
      nullable: false
      columnDefinition: timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      column: start_dt
    completeDate:
      type: DateTimeUTCType
      nullable: true
      columnDefinition: timestamp NULL DEFAULT NULL
      column: complete_dt
      options:
        default: NULL
    appliedBy:
      type: string
      length: 100
      nullable: false
      column: applied_by
    description:
      type: string
      length: 500
      nullable: false
