Visca\Bundle\LicomBundle\Entity\CompetitionStageType:
  type: entity
  table: CompetitionStageType
  repositoryClass: Visca\Bundle\LicomBundle\Repository\CompetitionStageTypeRepository
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 45
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  cache:
    region: Type
    usage: READ_ONLY
