Visca\Bundle\LicomBundle\Entity\CompetitionGraph:
  type: entity
  table: Competition_graph
  id:
    competition:
      type: integer
      length: 10
      associationKey: true
      column: Competition
      options:
        unsigned: true
    label:
      type: smallint
      length: 5
      associationKey: true
      options:
        unsigned: true
    competitionSeason:
      type: integer
      length: 10
      associationKey: true
      column: CompetitionSeason
      options:
        unsigned: true
  fields:
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
  indexes:
    fk_competitionSeason:
      columns: [CompetitionSeason]
    fk_competition:
      columns: [Competition]
    fk_label:
      columns: [label]
  manyToOne:
    competitionSeason:
      targetEntity: Visca\Bundle\LicomBundle\Entity\CompetitionSeason
      inversedBy: competitionGraph
      cache:
        region: Competition
        usage: READ_ONLY
      joinColumns:
        CompetitionSeason:
          referencedColumnName: id
          nullable: false
    label:
      targetEntity: Visca\Bundle\LicomBundle\Entity\CompetitionGraphLabel
      cache:
        region: Competition
        usage: READ_ONLY
      joinColumns:
        label:
          referencedColumnName: id
          nullable: false
    competition:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Competition
      inversedBy: competitionGraph
      cache:
        region: Competition
        usage: READ_ONLY
      joinColumns:
        Competition:
          referencedColumnName: id
          nullable: false
  cache:
    region: Competition
    usage: READ_ONLY
