Visca\Bundle\LicomBundle\Entity\LocalizationTranslationGraph:
  type: entity
  table: LocalizationTranslation_graph
  id:
    localizationTranslation:
      type: integer
      length: 10
      associationKey: true
      column: LocalizationTranslation
    label:
      type: smallint
      length: 5
      associationKey: true
      options:
        default: '1'
        unsigned: true
    localization:
      type: smallint
      length: 5
      associationKey: true
      column: Localization
      options:
        unsigned: true
  fields:
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
  indexes:
    fk_localizationTranslation:
      columns: [LocalizationTranslation]
    fk_localization:
      columns: [Localization]
    fk_label:
      columns: [label]
  manyToOne:
    localizationTranslation:
      targetEntity: Visca\Bundle\LicomBundle\Entity\LocalizationTranslation
      inversedBy: localizationTranslationGraph
      joinColumns:
        LocalizationTranslation:
          referencedColumnName: id
          nullable: false
    label:
      targetEntity: Visca\Bundle\LicomBundle\Entity\LocalizationTranslationGraphLabel
      joinColumns:
        label:
          referencedColumnName: id
          nullable: false
    localization:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Localization
      inversedBy: localizationTranslationGraph
      joinColumns:
        Localization:
          referencedColumnName: id
          nullable: false
