Visca\Bundle\LicomBundle\Entity\MatchAuxType:
  type: entity
  table: Match_auxType
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 255
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
  oneToMany:
    aux:
      targetEntity: Visca\Bundle\LicomBundle\Entity\MatchAux
      mappedBy: type
  cache:
    region: Type
    usage: READ_ONLY
