Visca\Bundle\LicomBundle\Entity\MatchResultType:
  type: entity
  table: MatchResultType
  repositoryClass: Visca\Bundle\LicomBundle\Repository\MatchResultTypeRepository
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 255
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  oneToMany:
    matchResult:
      targetEntity: Visca\Bundle\LicomBundle\Entity\MatchResult
      mappedBy: matchResultType
  cache:
    region: Type
    usage: READ_ONLY
