Visca\Bundle\LicomBundle\Entity\MatchStats:
  type: entity
  table: MatchStats
  repositoryClass: Visca\Bundle\LicomBundle\Repository\MatchStatsRepository
  id:
    id:
      type: integer
      length: 10
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    value:
      type: string
      length: 45
      nullable: true
      options:
        default: NULL
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  indexes:
    fk_matchStatsType:
      columns: [MatchStatsType]
    fk_matchParticipant:
      columns: [MatchParticipant]
  uniqueConstraints:
    uq_matchParticipant_matchStatsType:
      columns: [MatchParticipant, MatchStatsType]
  manyToOne:
    matchStatsType:
      targetEntity: Visca\Bundle\LicomBundle\Entity\MatchStatsType
      joinColumns:
        MatchStatsType:
          referencedColumnName: id
          nullable: false
    matchParticipant:
      targetEntity: Visca\Bundle\LicomBundle\Entity\MatchParticipant
      joinColumns:
        MatchParticipant:
          referencedColumnName: id
          nullable: false
