Visca\Bundle\LicomBundle\Entity\MatchIncidentType:
  type: entity
  table: MatchIncidentType
  repositoryClass: Visca\Bundle\LicomBundle\Repository\MatchIncidentTypeRepository
  id:
    id:
      type: integer
      length: 10
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 255
      nullable: false
    category:
      type: MatchIncidentTypeCategory
      length: 0
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  indexes:
    fk_sport:
      columns: [Sport]
  uniqueConstraints:
    uq_code_sport:
      columns: [code, Sport]
  manyToOne:
    sport:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Sport
      joinColumns:
        Sport:
          referencedColumnName: id
          nullable: false
  cache:
    region: Type
    usage: READ_ONLY
