Visca\Bundle\LicomBundle\Entity\OverUnderMatchBettingOutcome:
  type: entity
  repositoryClass: Visca\Bundle\LicomBundle\Repository\OverUnderMatchBettingOutcomeRepository
  fields:
    goalsTotal:
      type: float
      nullable: true
      column: dparam
