Visca\Bundle\LicomBundle\Entity\ParticipantMembership:
  type: entity
  table: ParticipantMembership
  repositoryClass: Visca\Bundle\LicomBundle\Repository\ParticipantMembershipRepository
  id:
    id:
      type: integer
      length: 10
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    entityId:
      type: integer
      length: 10
      nullable: false
      options:
        unsigned: true
    participantType:
      type: ParticipantMembershipParticipantType
      length: 0
      nullable: false
    start:
      type: date
      nullable: true
      options:
        default: NULL
    end:
      type: date
      nullable: true
      options:
        default: NULL
    active:
      type: boolean
      nullable: false
      columnDefinition: TINYINT(3) UNSIGNED NOT NULL DEFAULT '1'
      options:
        default: '1'
        unsigned: true
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  indexes:
    fk_entity:
      columns: [Entity]
    fk_participant:
      columns: [Participant]
  manyToOne:
    entity:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Entity
      joinColumns:
        Entity:
          referencedColumnName: id
          nullable: false
    participant:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Participant
      inversedBy: participantMembership
      joinColumns:
        Participant:
          referencedColumnName: id
          nullable: false
  cache:
    region: Participant
    usage: READ_ONLY
