Visca\Bundle\LicomBundle\Entity\ProfileTranslationGraphLabel:
  type: entity
  table: ProfileTranslation_graphLabel
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 32
      nullable: false
    name:
      type: string
      length: 128
      nullable: false
  attributeOverride:
  oneToMany:
    profileTranslationGraph:
      targetEntity: Visca\Bundle\LicomBundle\Entity\ProfileTranslationGraph
      mappedBy: profileTranslationGraphLabel
  cache:
    region: Type
    usage: READ_ONLY
