Visca\Bundle\LicomBundle\Entity\ProfileEntityGraph:
  type: entity
  table: ProfileEntity_graph
  repositoryClass: Visca\Bundle\LicomBundle\Repository\ProfileEntityGraphRepository
  id:
    profile:
      type: integer
      length: 2
      associationKey: true
      column: Profile
      options:
        unsigned: true
    label:
      type: smallint
      length: 5
      associationKey: true
      options:
        unsigned: true
    entity:
      type: smallint
      length: 5
      associationKey: true
      options:
        unsigned: true
    entityId:
      type: integer
      length: 10
      options:
        unsigned: true
  fields:
    position:
      type: smallint
      length: 5
      nullable: false
      options:
        default: '65535'
        unsigned: true
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
  indexes:
    fk_profile:
      columns: [Profile]
    fk_label:
      columns: [label]
    fk_entity:
      columns: [entity]
    idx_entityId:
      columns: [entityId]
  manyToOne:
    profile:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Profile
      cache:
        region: Profile
        usage: READ_ONLY
      joinColumns:
        Profile:
          referencedColumnName: id
          nullable: false
    label:
      targetEntity: Visca\Bundle\LicomBundle\Entity\ProfileEntityGraphLabel
      cache:
        region: Profile
        usage: READ_ONLY
      joinColumns:
        label:
          referencedColumnName: id
          nullable: false
    entity:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Entity
      cache:
        region: Profile
        usage: READ_ONLY
      joinColumns:
        entity:
          referencedColumnName: id
          nullable: false
  cache:
    region: Profile
    usage: READ_ONLY
