Visca\Bundle\LicomBundle\Entity\Profile:
  type: entity
  table: Profile
  repositoryClass: Visca\Bundle\LicomBundle\Repository\ProfileRepository
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 32
      nullable: false
    name:
      type: string
      length: 128
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  oneToMany:
    profileTranslationGraph:
      targetEntity: Visca\Bundle\LicomBundle\Entity\ProfileTranslationGraph
      mappedBy: profile
  cache:
    region: Profile
    usage: READ_ONLY
