Visca\Bundle\LicomBundle\Entity\ProfileEntityGraphLabel:
  type: entity
  table: ProfileEntity_graphLabel
  repositoryClass: Visca\Bundle\LicomBundle\Repository\ProfileEntityGraphLabelRepository
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      length: 32
      nullable: false
    entityId:
      type: integer
      length: 10
      nullable: true
      options:
        unsigned: true
    name:
      type: string
      length: 128
      nullable: false
  indexes:
    fk_entity:
      columns: [Entity]
  uniqueConstraints:
    uq_code_entity_entityId:
      columns: [code, Entity, entityId]
  manyToOne:
    entity:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Entity
      joinColumns:
        Entity:
          referencedColumnName: id
  cache:
    region: Type
    usage: READ_ONLY
