Visca\Bundle\LicomBundle\Entity\StandingColumn:
  type: entity
  table: StandingColumn
  repositoryClass: Visca\Bundle\LicomBundle\Repository\StandingColumnsRepository
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 45
      nullable: false
    name:
      type: string
      length: 255
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  indexes:
    fk_standingColumnScope:
      columns: [StandingColumnScope]
    fk_standingColumnGroup:
      columns: [StandingColumnGroup]
  oneToMany:
    standingViewGraph:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingViewGraph
      mappedBy: standingColumn
  manyToOne:
    standingColumnScope:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingColumnScope
      joinColumns:
        StandingColumnScope:
          referencedColumnName: id
    standingColumnGroup:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingColumnGroup
      joinColumns:
        StandingColumnGroup:
          referencedColumnName: id
