Visca\Bundle\LicomBundle\Entity\StandingCommentGraph:
  type: entity
  table: StandingComment_graph
  id:
    standingRow:
      type: integer
      length: 10
      associationKey: true
      column: StandingRow
      options:
        unsigned: true
    label:
      type: smallint
      length: 5
      associationKey: true
      column: label
      options:
        default: '1'
        unsigned: true
    standingComment:
      type: integer
      length: 10
      associationKey: true
      column: StandingComment
      options:
        unsigned: true
  fields:
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
  indexes:
    fk_standingRow:
      columns: [StandingRow]
    fk_standingComment:
      columns: [StandingComment]
    fk_label:
      columns: [label]
  manyToOne:
    standingRow:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingRow
      joinColumns:
        StandingRow:
          referencedColumnName: id
          nullable: false
    label:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingCommentGraphLabel
      joinColumns:
        label:
          referencedColumnName: id
          nullable: false
    standingComment:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingComment
      joinColumns:
        StandingComment:
          referencedColumnName: id
          nullable: false
