Visca\Bundle\LicomBundle\Entity\StandingComment:
  type: entity
  table: StandingComment
  id:
    id:
      type: integer
      length: 10
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    text:
      type: string
      length: 255
      nullable: false
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
