Visca\Bundle\LicomBundle\Entity\StandingViewGraphLabel:
  type: entity
  table: StandingView_graphLabel
  id:
    id:
      type: smallint
      length: 5
      options:
        unsigned: true
  fields:
    code:
      type: string
      unique: true
      length: 32
      nullable: false
    name:
      type: string
      length: 255
      nullable: false
