Visca\Bundle\LicomBundle\Entity\StandingCell:
  type: entity
  table: StandingCell
  repositoryClass: Visca\Bundle\LicomBundle\Repository\StandingCellRepository
  id:
    id:
      type: integer
      length: 10
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    value:
      type: float
      nullable: false
      columnDefinition: FLOAT DEFAULT NULL
    del:
      type: SoftDeletionType
      length: 0
      nullable: false
      options:
        default: 'no'
    createdAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
    updatedAt:
      type: DateTimeUTCType
      nullable: true
      options:
        default: NULL
  indexes:
    fk_standingRow:
      columns: [StandingRow]
    fk_standingColumn:
      columns: [StandingColumn]
  uniqueConstraints:
    uq_standingRow_standingColumn:
      columns: [StandingRow, StandingColumn]
  manyToOne:
    standingRow:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingRow
      inversedBy: standingCell
      joinColumns:
        StandingRow:
          referencedColumnName: id
          nullable: false
    standingColumn:
      targetEntity: Visca\Bundle\LicomBundle\Entity\StandingColumn
      joinColumns:
        StandingColumn:
          referencedColumnName: id
          nullable: false
