Visca\Bundle\LicomBundle\Entity\ThreeWayMatchBettingOutcome:
  type: entity
  repositoryClass: Visca\Bundle\LicomBundle\Repository\ThreeWayMatchBettingOutcome
  manyToOne:
    winner:
      targetEntity: Visca\Bundle\LicomBundle\Entity\Participant
      joinColumns:
        iparam:
          referencedColumnName: id
