services:
  visca_licom.factory.athlete:
    class: Visca\Bundle\LicomBundle\Factory\AthleteFactory
  visca_licom.factory.competition_season:
    class: Visca\Bundle\LicomBundle\Factory\CompetitionSeasonFactory
  visca_licom.factory.competition_season_stage:
    class: Visca\Bundle\LicomBundle\Factory\CompetitionSeasonStageFactory
  visca_licom.factory.match:
    class: Visca\Bundle\LicomBundle\Factory\MatchFactory
  visca_licom.factory.standing:
    class: Visca\Bundle\LicomBundle\Factory\StandingFactory
  visca_licom.factory.match_result:
    class: Visca\Bundle\LicomBundle\Factory\MatchResultFactory