services:
    visca_licom.filter.match.most_revelant:
        class: Visca\Bundle\LicomBundle\Services\Filters\MatchMostRelevantFilter
        arguments:
            -
                - '@visca_licom.filter.match.rule.in_progress'
                - '@visca_licom.filter.match.rule.last_played_recently'
                - '@visca_licom.filter.match.rule.next_to_come'
                - '@visca_licom.filter.match.rule.last_played'

    visca_licom.filter.match.rule.in_progress:
        class: Visca\Bundle\LicomBundle\Services\Filters\Rules\MatchInProgressRule

    visca_licom.filter.match.rule.last_played_recently:
        class: Visca\Bundle\LicomBundle\Services\Filters\Rules\MatchLastPlayedRule
        arguments:
            - 8

    visca_licom.filter.match.rule.last_played:
        class: Visca\Bundle\LicomBundle\Services\Filters\Rules\MatchLastPlayedRule

    visca_licom.filter.match.rule.next_to_come:
        class: Visca\Bundle\LicomBundle\Services\Filters\Rules\MatchNextToComeRule
