services:
    visca_licom.formatter.american:
        class: Visca\Bundle\LicomBundle\Formatter\Odds\AmericanOddsFormatter
        tags:
           - { name: visca_licom.formatter.odds, label: 'american' }

    visca_licom.formatter.decimal:
        class: Visca\Bundle\LicomBundle\Formatter\Odds\DecimalOddsFormatter
        tags:
           - { name: visca_licom.formatter.odds, label: 'decimal' }

    visca_licom.formatter.fractional:
        class: Visca\Bundle\LicomBundle\Formatter\Odds\FractionalOddsFormatter
        tags:
           - { name: visca_licom.formatter.odds, label: 'fractional' }