services:
    # Helpers
    visca_licom.helper.participant:
        class: Visca\Bundle\LicomViewBundle\Helper\Entity\ParticipantHelper

    visca_licom.helper.match:
        class: Visca\Bundle\LicomViewBundle\Helper\Entity\MatchHelper

    visca_licom.helper.match_status_description:
        class: Visca\Bundle\LicomViewBundle\Helper\Entity\MatchStatusDescriptionHelper
