services:
    # Entities
    visca_licom.entity_manager:
        class: Doctrine\ORM\EntityManager
        public: false
        factory_service: "doctrine"
        factory_method: getManager
        arguments: ["licom"]
