services:
   visca_licom.cache.manager.translations:
        class: Visca\Bundle\LicomBundle\Services\Translations\TranslationCacheManager
        arguments: ['@visca_licom.cache.translation.mysql', %licom_profile_id%]

   visca_licom.cache.translation:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
          - [setMemcached, ['@app.memcached']]

   visca_licom.cache.translation.memcached:
        class: Visca\Bundle\LicomBundle\Services\Translations\MemCache
        arguments:
          - %memcached_host%
          - %memcached_port%

   visca_licom.cache.translation.mysql:
        class: Visca\Bundle\LicomBundle\Services\Translations\MysqlCache
        arguments:
          - '@doctrine.dbal.default_connection'
