approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^(:-1:)'
reset_on_push: true
reviewers:
  members:
  - dagio
  - raulferras
  - kristianmu
  - raulferras
  - JonasHaouzi
  name: default
  required: 2