approve_by_comment: true
approve_regex: '^(Approved|:\+1:)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: true
reviewers:
  required: 1
  members:
  - dagio
  - raulferras
  - kristianmu
  - felixcarpena
  - JonasHaouzi
  - celtric
  - jcornide
  name: default