approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^(:-1:)'
reset_on_push: true
author_approval: required
reviewers:
  members:
  - dagio
  - raulferras
  - jcornide
  - kristianmu
  - felixcarpena
  - raulferras
  - JonasHaouzi
  - mrcmorales
  name: default
  required: 2