preset:
   - 'psr1'
   - 'psr2'

enabled:
   - 'array_element_no_space_before_comma'
   - 'array_element_white_space_after_comma'
   - 'blankline_after_open_tag'
   - 'double_arrow_multiline_whitespaces'
   - 'no_empty_statement'
   - 'simplified_null_return'
   - 'no_extra_consecutive_blank_lines'
   - 'function_typehint_space'
   - 'join_function'
   - 'no_trailing_comma_in_list_call'
   - 'no_leading_namespace_whitespace'
   - 'new_with_braces'
   - 'no_blank_lines_after_phpdoc'
   - 'binary_operator_spaces'
   - 'phpdoc_indent'
   - 'phpdoc_inline_tag'
   - 'phpdoc_no_empty_return'
   - 'phpdoc_align'
   - 'phpdoc_scalar'
   - 'phpdoc_separation'
   - 'phpdoc_short_description'
   - 'phpdoc_trim'
   - 'phpdoc_type_to_var'
   - 'phpdoc_types'
   - 'phpdoc_var_without_name'
   - 'pre_increment'
   - 'print_to_echo'
   - 'remove_lines_between_uses'
   - 'blank_line_before_return'
   - 'self_accessor'
   - 'short_bool_cast'
   - 'single_array_no_trailing_comma'
   - 'single_blank_line_before_namespace'
   - 'spaces_before_semicolon'
   - 'spaces_cast'
   - 'standardize_not_equal'
   - 'ternary_spaces'
   - 'trim_array_spaces'
   - 'unalign_double_arrow'
   - 'unalign_equals'
   - 'unary_operators_spaces'
   - 'no_unused_imports'
   - 'whitespacy_lines'
   - 'phpdoc_order'
   - 'array_element_white_space_after_comma'
   - 'binary_operator_spaces'
   - 'blank_line_before_return'
   - 'braces'

disabled:
   - 'concat_without_spaces'
   - 'trailing_comma_in_multiline_array'
   - 'no_blank_lines_after_class_opening'
   - 'object_operator_without_whitespace'
   - 'remove_leading_slash_use'
   - 'single_quote'
   - 'unneeded_control_parentheses'
   - 'no_empty_phpdoc'
   - 'phpdoc_single_line_var_spacing'