services:
    # Image provider
    visca_licom.provider.image.participant:
        class: Visca\Bundle\LicomViewBundle\Provider\Image\ParticipantImageProvider
        arguments:
            - "@=service(container.hasParameter('visca.media.adapter') ? parameter('visca.media.adapter') : 'visca_media.adapter.file.system')"
            - @visca_media.factory.media_factory

    visca_licom.provider.image.country:
        class: Visca\Bundle\LicomViewBundle\Provider\Image\CountryImageProvider
        arguments:
            - "@=service(container.hasParameter('visca.media.adapter') ? parameter('visca.media.adapter') : 'visca_media.adapter.file.system')"
            - @visca_media.factory.media_factory

    visca_licom.provider.image.competition:
        class: Visca\Bundle\LicomViewBundle\Provider\Image\CompetitionImageProvider
        arguments:
            - "@=service(container.hasParameter('visca.media.adapter') ? parameter('visca.media.adapter') : 'visca_media.adapter.file.system')"
            - @visca_media.factory.media_factory

    visca_licom.provider.image.sport:
        class: Visca\Bundle\LicomViewBundle\Provider\Image\SportImageProvider
        arguments:
            - "@=service(container.hasParameter('visca.media.adapter') ? parameter('visca.media.adapter') : 'visca_media.adapter.file.system')"
            - @visca_media.factory.media_factory
