services:
    # Providers
    visca_licom.provider.slug.wrapper:
        class: Visca\Bundle\LicomViewBundle\Wrapper\SlugWrapper
        arguments:
            - @visca_licom.provider.slug.competition
            - @visca_licom.provider.slug.country
            - @visca_licom.provider.slug.participant
            - @visca_licom.provider.slug.competition_category
            - @visca_licom.provider.slug.match

    visca_licom.provider.slug.competition:
        class: Visca\Bundle\LicomViewBundle\Provider\Slug\CompetitionSlugProvider
        arguments:
             - @visca_licom.repository.localization_translation
             - %licom_profile_id%

    visca_licom.provider.slug.competition_category:
        class: Visca\Bundle\LicomViewBundle\Provider\Slug\CompetitionCategorySlugProvider
        arguments:
             - @visca_licom.repository.localization_translation
             - %licom_profile_id%

    visca_licom.provider.slug.country:
        class: Visca\Bundle\LicomViewBundle\Provider\Slug\CountrySlugProvider
        arguments:
             - @visca_licom.repository.localization_translation
             - %licom_profile_id%

    visca_licom.provider.slug.participant:
        class: Visca\Bundle\LicomViewBundle\Provider\Slug\ParticipantSlugProvider
        arguments:
             - @visca_licom.repository.localization_translation
             - %licom_profile_id%

    visca_licom.provider.slug.match:
        class: Visca\Bundle\LicomViewBundle\Provider\Slug\MatchSlugProvider
        arguments:
             - @visca_licom.provider.slug.participant
