services:
    # Translations provider
    visca_licom.provider.translations.abstract:
        abstract: true
        arguments: [@visca_licom.cache.manager.translations]

    visca_licom.provider.translations.participant:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\ParticipantTranslationsProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.competition:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\CompetitionTranslationsProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.competition_category:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\CompetitionCategoryTranslationProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.competition_stage:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\CompetitionStageTranslationProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.country:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\CountryTranslationProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.match_status_description:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\MatchStatusDescTranslationProvider
        parent: visca_licom.provider.translations.abstract

    visca_licom.provider.translations.sport:
        class: Visca\Bundle\LicomViewBundle\Provider\Translations\SportTranslationsProvider
        parent: visca_licom.provider.translations.abstract
