<?php

namespace Visca\Bundle\LicomBundle\Entity\Code;

/**
 * Class EntityCode.
 *
 * DO NOT MODIFY - THIS CLASS IS AUTO GENERATED.
 */
class EntityCode
{
    const ENTITY_CODE = 101;
    const MATCH_CODE = 211;
    const MATCH_AUX_PROFILE_TYPE_CODE = 212;
    const MATCH_AUX_TYPE_CODE = 213;
    const MATCH_STATUS_DESCRIPTION_CODE = 214;
    const MATCH_INCIDENT_CODE = 221;
    const MATCH_INCIDENT_TYPE_CODE = 222;
    const MATCH_INCIDENT_AUX_TYPE_CODE = 223;
    const MATCH_TIMING_CODE = 225;
    const MATCH_PARTICIPANT_CODE = 231;
    const MATCH_PARTICIPANT_AUX_TYPE_CODE = 232;
    const MATCH_STATS_CODE = 241;
    const MATCH_STATS_TYPE_CODE = 242;
    const MATCH_RESULT_CODE = 251;
    const MATCH_RESULT_TYPE_CODE = 252;
    const MATCH_COMMENT_CODE = 261;
    const MATCH_COMMENT_TYPE_CODE = 262;
    const MATCH_LINEUP_CODE = 271;
    const MATCH_LINEUP_PARTICIPANT_TYPE_CODE = 272;
    const MATCH_LINEUP_PARTICIPANT_CODE = 273;
    const LOCALIZATION_CODE = 301;
    const LOCALIZATION_TRANSLATION_CODE = 306;
    const LOCALIZATION_TRANSLATION_TYPE_CODE = 308;
    const PARTICIPANT_CODE = 401;
    const PARTICIPANT_AUX_TYPE_CODE = 402;
    const PARTICIPANT_MEMBERSHIP_CODE = 403;
    const SPORT_CODE = 501;
    const COUNTRY_CODE = 502;
    const COMPETITION_CODE = 503;
    const COMPETITION_CATEGORY_CODE = 504;
    const COMPETITION_SEASON_CODE = 505;
    const COMPETITION_STAGE_CODE = 506;
    const COMPETITION_ROUND_CODE = 507;
    const COMPETITION_LEG_CODE = 508;
    const COMPETITION_SEASON_STAGE_CODE = 509;
    const COMPETITION_STAGE_TYPE_CODE = 510;
    const STANDING_CODE = 601;
    const STANDING_COLUMN_CODE = 602;
    const STANDING_COMMENT_CODE = 603;
    const STANDING_PROMOTION_CODE = 604;
    const STANDING_ROW_CODE = 605;
    const STANDING_CELL_CODE = 606;
    const STANDING_TYPE_CODE = 607;
    const STANDING_PROMOTION_TYPE_CODE = 608;
    const STANDING_COLUMN_GROUP_CODE = 609;
    const STANDING_COLUMN_SCOPE_CODE = 610;
    const STANDING_VIEW_CODE = 611;
    const BETTING_OFFER_CODE = 701;
    const BETTING_OFFER_AVAILABILITY_CODE = 702;
    const BETTING_OUTCOME_CODE = 703;
    const BETTING_OUTCOME_SCOPE_TYPE_CODE = 704;
    const BETTING_OUTCOME_SUB_TYPE_CODE = 705;
    const BETTING_OUTCOME_TYPE_CODE = 706;
    const BETTING_OFFER_PROVIDER_CODE = 707;
    const BOOKMAKER_CODE = 708;
    const PROFILE_CODE = 801;
    const PROFILE_TRANSLATION_GRAPH_LABEL_CODE = 802;
    const PROFILE_ENTITY_GRAPH_LABEL_CODE = 803;
    const PROFILE_RULE_CODE = 804;
    const PROFILE_RULE_TYPE_CODE = 805;
    const MEDIA_CODE = 901;
    const MEDIA_TYPE_CODE = 902;
    const MEDIA_THEME_CODE = 903;
    const EVENT_CODE = 1001;
    const EVENT_TYPE_CODE = 1002;
}
