<?php

namespace Visca\Bundle\LicomBundle\Entity\Code;

/**
 * Class MatchAuxTypeCode.
 *
 * DO NOT MODIFY - THIS CLASS IS AUTO GENERATED.
 */
class MatchAuxTypeCode
{
    const DATE_ENDED_CODE = 1;
    const DATE_STARTED_CODE = 2;
    const DATE_FIRST_HALF_ENDED_CODE = 13;
    const DATE_SECOND_HALF_STARTED_CODE = 3;
    const DATE_SECOND_HALF_ENDED_CODE = 14;
    const REFEREE_CODE = 4;
    const SPECTATORS_CODE = 5;
    const VENUE_NAME_CODE = 6;
    const FIRST_TO_SERVE_CODE = 7;
    const CURRENT_PERIOD_STARTED_AT_CODE = 8;
    const FIRST_HALF_TIME_STARTED_AT_CODE = 9;
    const SECOND_HALF_TIME_STARTED_AT_CODE = 10;
    const EXTRA_TIME_1ST_HALF_TIME_STARTED_AT_CODE = 11;
    const EXTRA_TIME_1ST_HALF_TIME_ENDED_AT_CODE = 15;
    const EXTRA_TIME_2ND_HALF_TIME_STARTED_AT_CODE = 12;
    const EXTRA_TIME_2ND_HALF_TIME_ENDED_AT_CODE = 16;
}
