<?php

namespace Visca\Bundle\LicomBundle\Entity\Code;

/**
 * Class StandingPromotionCode.
 *
 * DO NOT MODIFY - THIS CLASS IS AUTO GENERATED.
 */
class StandingPromotionCode
{
    const NONE_CODE = 0;
    const AFCCHAMPIONSLEAGUE_CODE = 1;
    const AFCCUP_CODE = 2;
    const CAFCONFEDERATIONCUP_CODE = 3;
    const CHAMPIONSLEAGUE_CODE = 4;
    const CHAMPIONSLEAGUEQUAL_CODE = 5;
    const CHAMPIONSROUND_CODE = 6;
    const COPALIBERTADORES_CODE = 7;
    const COPASUDAMERICANA_CODE = 8;
    const CUPWINNERSCUP_CODE = 9;
    const EHFCUP_CODE = 10;
    const FINALROUND_CODE = 11;
    const FINALS_CODE = 12;
    const PLACEMENTMATCHESGREEN_CODE = 13;
    const PLAYOFF_CODE = 14;
    const PROMOTION_CODE = 15;
    const PROMOTIONPLAYOFF_CODE = 16;
    const PROMOTIONROUND_CODE = 17;
    const QUALIFICATION_TO_NEXT_STAGE_CODE = 18;
    const RELEGATION_CODE = 19;
    const RELEGATIONPLAYOFF_CODE = 20;
    const RELEGATIONPLAYOFFS_CODE = 21;
    const UEFACUP_CODE = 22;
    const UEFAQUAL_CODE = 23;
    const UEFAQUALPLAYOFF_CODE = 24;
    const CFUCLUBCHAMPIONSHIP_CODE = 25;
    const FA_2UEFA_CODE = 26;
    const FA_2UEFAQUAL_CODE = 27;
    const TEST_CODE = 28;
    const AFCCHAMPIONSLEAGUEQUAL_CODE = 29;
    const AFCCUPQUAL_CODE = 30;
    const AFCPRESIDENTSCUP_CODE = 31;
    const CAFCHAMPIONSLEAGUEQUAL_CODE = 32;
    const CHAMPIONSHIP_PLAYOFF_CODE = 33;
    const CHALLENGECUP_CODE = 34;
    const CONCACAFCHAMPIONSLEAGUE_CODE = 35;
    const COPALIBERTADORESQUAL_CODE = 36;
    const OFCCHAMPIONSLEAGUE_CODE = 37;
    const OFCCHAMPIONSLEAGUEQUAL_CODE = 38;
    const PLACEMENTMATCHES_CODE = 39;
    const INTERTOTOCUP_CODE = 40;
}
