<?php

namespace Visca\Bundle\LicomBundle\Entity\Code;

/**
 * Class StandingColumnCode.
 *
 * DO NOT MODIFY - THIS CLASS IS AUTO GENERATED.
 */
class StandingColumnCode
{
    const CHANGE_AWAY_CODE = 1;
    const CHANGE_HOME_CODE = 2;
    const CHANGE_TOTAL_CODE = 3;
    const DRAW_AWAY_CODE = 4;
    const DRAW_HOME_CODE = 5;
    const DRAW_TOTAL_CODE = 6;
    const GOAL_DIFF_AWAY_CODE = 7;
    const GOAL_DIFF_HOME_CODE = 8;
    const GOAL_DIFF_TOTAL_CODE = 9;
    const GOALS_AGAINST_AWAY_CODE = 10;
    const GOALS_AGAINST_HOME_CODE = 11;
    const GOALS_AGAINST_TOTAL_CODE = 12;
    const GOALS_FOR_AWAY_CODE = 13;
    const GOALS_FOR_HOME_CODE = 14;
    const GOALS_FOR_TOTAL_CODE = 15;
    const LOSS_AWAY_CODE = 19;
    const LOSS_HOME_CODE = 20;
    const LOSS_TOTAL_CODE = 21;
    const MATCHES_AWAY_CODE = 22;
    const MATCHES_HOME_CODE = 23;
    const MATCHES_TOTAL_CODE = 24;
    const POINTS_AWAY_CODE = 25;
    const POINTS_HOME_CODE = 26;
    const POINTS_TOTAL_CODE = 27;
    const POSITION_AWAY_CODE = 28;
    const POSITION_HOME_CODE = 29;
    const POSITION_ATTACK_CODE = 155;
    const POSITION_DEFENSE_CODE = 156;
    const POSITION_FIRST_HALF_CODE = 160;
    const POSITION_SECOND_HALF_CODE = 161;
    const POSITION_TOP_SCORER_CODE = 154;
    const POSITION_TOTAL_CODE = 30;

    const SORT_POSITION_AWAY_CODE = 31;
    const SORT_POSITION_HOME_CODE = 32;
    const SORT_POSITION_TOTAL_CODE = 33;
    const SORT_POSITION_ATTACK_CODE = 158;
    const SORT_POSITION_DEFENSE_CODE = 159;
    const SORT_POSITION_FIRST_HALF_CODE = 162;
    const SORT_POSITION_SECOND_HALF_CODE = 163;

    const WIN_AWAY_CODE = 34;
    const WIN_HOME_CODE = 35;
    const WIN_TOTAL_CODE = 36;
    const YELLOW_CARDS_CODE = 37;
    const RED_CARDS_CODE = 38;
    const TOTAL_CARDS_CODE = 39;
    const GOALS_FOR_TOTAL_1_TO_15_MINUTE_CODE = 40;
    const GOALS_FOR_TOTAL_16_TO_30_MINUTE_CODE = 41;
    const GOALS_FOR_TOTAL_31_TO_45_MINUTE_CODE = 42;
    const GOALS_FOR_TOTAL_46_TO_60_MINUTE_CODE = 43;
    const GOALS_FOR_TOTAL_61_TO_75_MINUTE_CODE = 44;
    const GOALS_FOR_TOTAL_76_TO_90_MINUTE_CODE = 45;
    const GOALS_AWAY_TOTAL_1_TO_15_MINUTE_CODE = 46;
    const GOALS_AWAY_TOTAL_16_TO_30_MINUTE_CODE = 47;
    const GOALS_AWAY_TOTAL_31_TO_45_MINUTE_CODE = 48;
    const GOALS_AWAY_TOTAL_46_TO_60_MINUTE_CODE = 49;
    const GOALS_AWAY_TOTAL_61_TO_75_MINUTE_CODE = 50;
    const GOALS_AWAY_TOTAL_76_TO_90_MINUTE_CODE = 51;
    const MATCHES_OVER_TWO_AND_HALF_GOALS_CODE = 52;
    const MATCHES_UNDER_TWO_AND_HALF_GOALS_CODE = 53;
    const ATHLETE_TEAM_CODE = 54;
}
