<?php

namespace Visca\Bundle\LicomBundle\Entity\Code;

/**
 * Class StandingViewCode.
 *
 * DO NOT MODIFY - THIS CLASS IS AUTO GENERATED.
 */
class StandingViewCode
{
    const COMPETITION_TABLE_CODE = 1;
    const COMPETITION_TABLE_HOME_CODE = 2;
    const COMPETITION_TABLE_AWAY_CODE = 3;
    const COMPETITION_TABLE_ATTACK_CODE = 4;
    const COMPETITION_TABLE_DEFENSE_CODE = 5;
    const COMPETITION_TABLE_1ST_HT_CODE = 6;
    const COMPETITION_TABLE_2ND_HT_CODE = 7;
    const COMPETITION_TABLE_FAIREPLAY_CODE = 8;
    const COMPETITION_TABLE_TOP_SCORER_CODE = 9;
    const COMPETITION_TABLE_CARDS_CODE = 10;
    const LIVE_COMPETITION_TABLE_CODE = 11;
    const COMPETITION_CARDS_STATS_CODE = 12;
    const COMPETITION_GOALS_STATS_CODE = 13;
    const COMPETITION_TEAM_OVER_UNDER_STATS_CODE = 14;
}
