<?php

namespace Visca\Bundle\LicomBundle\Repository;

use Doctrine\ORM\Query;
use Visca\Bundle\DoctrineBundle\Repository\Abstracts\AbstractEntityRepository;
use Visca\Bundle\LicomBundle\Entity\CompetitionCategory;

/**
 * Class CompetitionCategoryRepository.
 */
class CompetitionCategoryRepository extends AbstractEntityRepository
{
    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param int|null $limit Limit
     *
     * @return array
     */
    public function getAllIds($limit = null)
    {
        $queryBuilder = $this->createQueryBuilder('c')->select('c.id');

        if (isset($limit)) {
            $queryBuilder->setMaxResults($limit);
        }

        return $queryBuilder->getQuery()->getArrayResult();
    }

    /**
     * Returns all the CompetitionCategory in the array given.
     *
     * @param array|null  $competitionCategoriesIds ids to search
     * @param string|null $orderBy                  Field to order by
     *
     * @return CompetitionCategory[]
     */
    public function findByIds(
        $competitionCategoriesIds = null,
        $orderBy = null
    ) {
        $queryBuilder = $this
            ->entityManager
            ->createQueryBuilder()
            ->from($this->entityName, 'cc')
            ->select('cc')
            ->where('cc.id IN (:ccIds)')
            ->setParameter('ccIds', $competitionCategoriesIds);
        if (!is_null($orderBy)) {
            $queryBuilder
                ->orderBy('cc.'.$orderBy, 'ASC');
        }

        return $queryBuilder->getQuery()->setHint(Query::HINT_REFRESH, true)->execute();
    }

    /**
     * @param array $ids Ids
     *
     * @return CompetitionCategory[]
     */
    public function getAndSortByIds($ids)
    {
        $queryBuilder = $this->createQueryBuilder('cc')
            ->where('cc.id IN (:ids)')
            ->orderBy('FIELD(cc.id, :ids)')
            ->setParameter('ids', $ids);

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param Country $country
     * @param Sport   $sport
     *
     * @throws NonUniqueResultException
     * @throws NoResultException
     *
     * @return CompetitionCategory
     */
    public function findOneByCountryAndSport(Country $country, Sport $sport)
    {
        return $this->createQueryBuilder('CountryCategory')
            ->innerJoin('CountryCategory.sport', 'Sport')
            ->innerJoin('CountryCategory.country', 'Country')
            ->where('Sport = :sport')
            ->andWhere('Country = :country')
            ->setParameter(':country', $country)
            ->setParameter(':sport', $sport)
            ->getQuery()
            ->getSingleResult();
    }
}
